<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                // The overachiever who replies to emails at 11pm
                'id'                      => 7,
                'name'                    => 'Juan Trabaho',
                'username'                => 'juan.trabaho',
                'password'                => Hash::make('password123'),
                'role'                    => 'employee',
                'profile_picture'         => null,
                'remember_token'          => 'JuanTrabahoTkn',
                'first_name'              => 'Juan',
                'middle_name'             => 'Daming',
                'last_name'               => 'Trabaho',
                'email'                   => 'juan.trabaho@smartco.com',
                'phone'                   => '09171234567',
                'address'                 => '12 Overtime St., Cubao, Quezon City',
                'civil_status'            => 'married',
                'spouse_name'             => 'Rosa Trabaho',
                'date_of_birth'           => '1995-03-14',
                'place_of_birth'          => 'Quezon City',
                'educational_attainment'  => "Bachelor's Degree",
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2021-06-01',
                'position'                => 'Senior Accountant',
                'department'              => 'Finance',
                'status'                  => 'active',
                'salary_rate'             => 850.00,
                'has_sss'                 => 1,
                'sss_number'              => '34-1234567-8',
                'has_tin'                 => 1,
                'tin_number'              => '123-456-789-000',
                'has_pagibig'             => 1,
                'pagibig_number'          => 'PB-1234-5678',
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => now(),
                'updated_at'              => now(),
            ],
            [
                // Always "on the way" but arrives 15 mins late
                'id'                      => 8,
                'name'                    => 'Maria Halos',
                'username'                => 'maria.halos',
                'password'                => Hash::make('password123'),
                'role'                    => 'employee',
                'profile_picture'         => null,
                'remember_token'          => 'MariaHalosTkn1',
                'first_name'              => 'Maria',
                'middle_name'             => 'Laging',
                'last_name'               => 'Halos',
                'email'                   => 'maria.halos@smartco.com',
                'phone'                   => '09189876543',
                'address'                 => '7 Malapit Na Ave., Pasig City',
                'civil_status'            => 'married',
                'spouse_name'             => 'Roberto Halos',
                'date_of_birth'           => '1992-07-22',
                'place_of_birth'          => 'Pasig City',
                'educational_attainment'  => "Bachelor's Degree",
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2020-01-15',
                'position'                => 'HR Officer',
                'department'              => 'Human Resources',
                'status'                  => 'active',
                'salary_rate'             => 750.00,
                'has_sss'                 => 1,
                'sss_number'              => '34-9876543-2',
                'has_tin'                 => 1,
                'tin_number'              => '987-654-321-000',
                'has_pagibig'             => 1,
                'pagibig_number'          => 'PB-8765-4321',
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => now(),
                'updated_at'              => now(),
            ],
            [
                // The guy who takes a 45-minute "quick break"
                'id'                      => 9,
                'name'                    => 'Carlo Pahinga',
                'username'                => 'carlo.pahinga',
                'password'                => Hash::make('password123'),
                'role'                    => 'employee',
                'profile_picture'         => null,
                'remember_token'          => 'CarloPahingaTkn',
                'first_name'              => 'Carlo',
                'middle_name'             => 'Sandali',
                'last_name'               => 'Pahinga',
                'email'                   => 'carlo.pahinga@smartco.com',
                'phone'                   => '09201112222',
                'address'                 => '3 Konting Tulog Lane, Marikina City',
                'civil_status'            => 'married',
                'spouse_name'             => 'Ligaya Pahinga',
                'date_of_birth'           => '1998-11-05',
                'place_of_birth'          => 'Marikina City',
                'educational_attainment'  => "Bachelor's Degree",
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2022-03-10',
                'position'                => 'Bookkeeper',
                'department'              => 'Finance',
                'status'                  => 'active',
                'salary_rate'             => 650.00,
                'has_sss'                 => 1,
                'sss_number'              => '34-1122334-5',
                'has_tin'                 => 1,
                'tin_number'              => '112-233-445-000',
                'has_pagibig'             => 1,
                'pagibig_number'          => 'PB-1122-3344',
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => now(),
                'updated_at'              => now(),
            ],
        ]);
    }
}