<?php

namespace Database\Seeders;

use App\Models\EmployeeAttachment;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class EmployeeAttachmentsSeeder extends Seeder
{
    public function run(): void
    {
        $employees = DB::table('users')
            ->where('role', 'employee')
            ->select('id', 'username', 'first_name', 'last_name')
            ->get()
            ->keyBy('username');

        $hr = DB::table('users')->where('role', 'hr')->orderBy('id')->first();
        $hrId = $hr->id ?? null;

        $usernames = ['john.doe', 'angela.fernandez', 'juan.trabaho', 'maria.halos', 'carlo.pahinga'];
        $targets = $employees->only($usernames);
        if ($targets->isEmpty()) {
            $this->command?->warn('Demo employee users not found; skipping EmployeeAttachmentsSeeder.');
            return;
        }

        $baseDir = 'seed-attachments';
        Storage::disk('public')->makeDirectory($baseDir);

        // Create small placeholder files so URLs don't 404
        $mk = function (string $path, string $contents) {
            if (!Storage::disk('public')->exists($path)) {
                Storage::disk('public')->put($path, $contents);
            }
            return $path;
        };

        $types = EmployeeAttachment::attachmentTypes();

        // Clear previous seed attachments for these employees
        DB::table('employee_attachments')->whereIn('user_id', $targets->pluck('id')->values()->all())->delete();

        $rows = [];
        $now = now();

        foreach ($targets as $u) {
            $full = trim(($u->first_name ?? '') . ' ' . ($u->last_name ?? '')) ?: $u->username;
            $slug = strtolower(str_replace([' ', '.'], ['_', '_'], $u->username));

            // Seed a curated subset so the page shows a mix of statuses
            $seedKeys = [
                'drivers_license' => ['status' => 'approved', 'mime' => 'application/pdf'],
                'valid_id_1' => ['status' => 'pending', 'mime' => 'application/pdf'],
                'barangay_clearance' => ['status' => 'rejected', 'mime' => 'application/pdf'],
                'medical_cert' => ['status' => 'approved', 'mime' => 'application/pdf'],
            ];

            foreach ($seedKeys as $key => $meta) {
                $label = $types[$key] ?? $key;
                $filename = "{$slug}_{$key}.pdf";
                $filePath = "{$baseDir}/{$filename}";

                $mk($filePath, implode("\n", [
                    "%PDF-1.4",
                    "% Seeded placeholder file",
                    "Employee: {$full}",
                    "Attachment: {$label}",
                    "Note: This is a demo placeholder generated by seeder.",
                    "%%EOF",
                    "",
                ]));

                $rows[] = [
                    'user_id' => $u->id,
                    'attachment_key' => $key,
                    'label' => $label,
                    'file_path' => $filePath,
                    'original_name' => strtoupper($key) . '.pdf',
                    'mime_type' => $meta['mime'],
                    'file_size' => Storage::disk('public')->size($filePath),
                    'status' => $meta['status'],
                    'rejection_reason' => $meta['status'] === 'rejected'
                        ? "File is unclear / kulang ang details. Please re-upload a clearer copy."
                        : null,
                    'reviewed_by' => in_array($meta['status'], ['approved', 'rejected'], true) ? $hrId : null,
                    'reviewed_at' => in_array($meta['status'], ['approved', 'rejected'], true) ? $now->copy()->subDays(10) : null,
                    'uploaded_by_role' => 'employee',
                    'created_at' => $now->copy()->subDays(12),
                    'updated_at' => $now->copy()->subDays(10),
                ];
            }
        }

        // Some projects may not have rejection_reason/review fields yet (but your migration does).
        $hasRejection = \Illuminate\Support\Facades\Schema::hasColumn('employee_attachments', 'rejection_reason');
        $hasReviewedBy = \Illuminate\Support\Facades\Schema::hasColumn('employee_attachments', 'reviewed_by');
        $hasReviewedAt = \Illuminate\Support\Facades\Schema::hasColumn('employee_attachments', 'reviewed_at');
        $hasUploadedByRole = \Illuminate\Support\Facades\Schema::hasColumn('employee_attachments', 'uploaded_by_role');

        foreach ($rows as &$r) {
            if (!$hasRejection) unset($r['rejection_reason']);
            if (!$hasReviewedBy) unset($r['reviewed_by']);
            if (!$hasReviewedAt) unset($r['reviewed_at']);
            if (!$hasUploadedByRole) unset($r['uploaded_by_role']);
        }

        DB::table('employee_attachments')->insert($rows);
        $this->command?->info('✅ EmployeeAttachmentsSeeder: seeded ' . count($rows) . ' attachment records + placeholder files.');
    }
}

