<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class Users_Seeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('users')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('users')->insert([

            // -------------------------------------------------------
            // SYSTEM USERS (roles: superadmin, hr, remittance_clerk, accountant)
            // -------------------------------------------------------
            [
                'id'                      => 1,
                'name'                    => 'Super Admin',
                'username'                => 'superadmin',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'superadmin',
                'profile_picture'         => null,
                'remember_token'          => 'SuperAdminToken01',
                'first_name'              => 'Super',
                'middle_name'             => null,
                'last_name'               => 'Admin',
                'email'                   => 'superadmin@example.com',
                'phone'                   => null,
                'address'                 => null,
                'civil_status'            => null,
                'spouse_name'             => null,
                'date_of_birth'           => null,
                'place_of_birth'          => null,
                'educational_attainment'  => null,
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => null,
                'position'                => null,
                'department'              => null,
                'status'                  => 'active',
                'salary_rate'             => 0,
                'has_sss'                 => 0,
                'sss_number'              => null,
                'has_tin'                 => 0,
                'tin_number'              => null,
                'has_pagibig'             => 0,
                'pagibig_number'          => null,
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-06 12:11:11',
                'updated_at'              => '2026-02-06 12:11:11',
            ],
            [
                'id'                      => 2,
                'name'                    => 'QR Attendance Admin',
                'username'                => 'qr_admin',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'qr_admin',
                'profile_picture'         => null,
                'remember_token'          => 'QRAdminTkn01',
                'first_name'              => 'QR',
                'middle_name'             => null,
                'last_name'               => 'Admin',
                'email'                   => 'qr.admin@example.com',
                'phone'                   => '09131234567',
                'address'                 => null,
                'civil_status'            => null,
                'spouse_name'             => null,
                'date_of_birth'           => null,
                'place_of_birth'          => null,
                'educational_attainment'  => null,
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => null,
                'position'                => null,
                'department'              => null,
                'status'                  => 'active',
                'salary_rate'             => 0,
                'has_sss'                 => 0,
                'sss_number'              => null,
                'has_tin'                 => 0,
                'tin_number'              => null,
                'has_pagibig'             => 0,
                'pagibig_number'          => null,
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-06 12:11:12',
                'updated_at'              => '2026-02-06 12:11:12',
            ],
            [
                'id'                      => 3,
                'name'                    => 'HR Manager',
                'username'                => 'hrmanager',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'hr',
                'profile_picture'         => null,
                'remember_token'          => 'PD8ffT4qLQ',
                'first_name'              => 'HR',
                'middle_name'             => null,
                'last_name'               => 'Manager',
                'email'                   => 'hr@example.com',
                'phone'                   => '09101234567',
                'address'                 => json_encode([
                    'street'   => '100 Admin Street',
                    'barangay' => 'Brgy. Central',
                    'city'     => 'Quezon City',
                    'province' => 'Metro Manila',
                ]),
                'civil_status'            => null,
                'spouse_name'             => null,
                'date_of_birth'           => '1985-02-10',
                'place_of_birth'          => null,
                'educational_attainment'  => "College (Bachelor's)",
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2020-01-01',
                'position'                => 'HR Manager',
                'department'              => 'admin',
                'status'                  => 'active',
                'salary_rate'             => 1000.00,
                'has_sss'                 => 0,
                'sss_number'              => null,
                'has_tin'                 => 0,
                'tin_number'              => null,
                'has_pagibig'             => 0,
                'pagibig_number'          => null,
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-06 12:11:11',
                'updated_at'              => '2026-02-06 12:11:11',
            ],
            [
                'id'                      => 4,
                'name'                    => 'Remittance Clerk',
                'username'                => 'remittance_clerk',
                'password'                => '$2y$12$/La9Q6JGZkIbM1G5Ah.dwOAqcGhBJbU94pUeyauuq0jgZx4Hj/tr6',
                'role'                    => 'remittance_clerk',
                'profile_picture'         => null,
                'remember_token'          => '26TRckTpBv',
                'first_name'              => 'Remittance',
                'middle_name'             => null,
                'last_name'               => 'Clerk',
                'email'                   => 'remittance@example.com',
                'phone'                   => '09111234567',
                'address'                 => json_encode([
                    'street'   => '200 Clerk Street',
                    'barangay' => 'Brgy. Poblacion',
                    'city'     => 'Manila',
                    'province' => 'Metro Manila',
                ]),
                'civil_status'            => null,
                'spouse_name'             => null,
                'date_of_birth'           => '1993-06-15',
                'place_of_birth'          => null,
                'educational_attainment'  => "College (Bachelor's)",
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2021-03-15',
                'position'                => 'Remittance Clerk',
                'department'              => 'operation',
                'status'                  => 'active',
                'salary_rate'             => 700.00,
                'has_sss'                 => 0,
                'sss_number'              => null,
                'has_tin'                 => 0,
                'tin_number'              => null,
                'has_pagibig'             => 0,
                'pagibig_number'          => null,
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-06 12:11:11',
                'updated_at'              => '2026-02-06 12:11:11',
            ],
            [
                'id'                      => 5,
                'name'                    => 'Accountant',
                'username'                => 'accountant',
                'password'                => '$2y$12$eM2JIPsh.y4LVUlUv.xv6.VC.156R3pPLUAphTEKeFXINlqGIA5nm',
                'role'                    => 'accountant',
                'profile_picture'         => null,
                'remember_token'          => 'K0ve6RLqfM',
                'first_name'              => 'Account',
                'middle_name'             => null,
                'last_name'               => 'Ant',
                'email'                   => 'accountant@example.com',
                'phone'                   => '09121234567',
                'address'                 => json_encode([
                    'street'   => '300 Accounting Street',
                    'barangay' => 'Brgy. San Antonio',
                    'city'     => 'Makati City',
                    'province' => 'Metro Manila',
                ]),
                'civil_status'            => null,
                'spouse_name'             => null,
                'date_of_birth'           => '1990-09-20',
                'place_of_birth'          => null,
                'educational_attainment'  => "College (Bachelor's)",
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2020-06-01',
                'position'                => 'Accountant',
                'department'              => 'admin',
                'status'                  => 'active',
                'salary_rate'             => 950.00,
                'has_sss'                 => 0,
                'sss_number'              => null,
                'has_tin'                 => 0,
                'tin_number'              => null,
                'has_pagibig'             => 0,
                'pagibig_number'          => null,
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-06 12:11:12',
                'updated_at'              => '2026-02-06 12:11:12',
            ],

            // -------------------------------------------------------
            // EMPLOYEES (role: employee)
            // -------------------------------------------------------
            [
                'id'                      => 6,
                'name'                    => 'John Doe',
                'username'                => 'john.doe',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'employee',
                'profile_picture'         => null,
                'remember_token'          => 'XxYyZzDemo1',
                'first_name'              => 'John',
                'middle_name'             => null,
                'last_name'               => 'Doe',
                'email'                   => 'employee@example.com',
                'phone'                   => '09123456789',
                'address'                 => json_encode([
                    'street'   => '123 Main Street',
                    'barangay' => 'Brgy. Commonwealth',
                    'city'     => 'Quezon City',
                    'province' => 'Metro Manila',
                ]),
                'civil_status'            => 'single',
                'spouse_name'             => null,
                'date_of_birth'           => '1995-05-15',
                'place_of_birth'          => 'Quezon City',
                'educational_attainment'  => "College (Bachelor's)",
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2024-01-15',
                'position'                => 'Staff',
                'department'              => 'admin',
                'status'                  => 'active',
                'salary_rate'             => 800.00,
                'has_sss'                 => 0,
                'sss_number'              => null,
                'has_tin'                 => 0,
                'tin_number'              => null,
                'has_pagibig'             => 0,
                'pagibig_number'          => null,
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-06 12:11:12',
                'updated_at'              => '2026-02-06 12:11:12',
            ],
            [
                'id'                      => 7,
                'name'                    => 'Angela Fernandez',
                'username'                => 'angela.fernandez',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'employee',
                'profile_picture'         => null,
                'remember_token'          => 'AngelaDemo123',
                'first_name'              => 'Angela',
                'middle_name'             => null,
                'last_name'               => 'Fernandez',
                'email'                   => 'angela.fernandez@example.com',
                'phone'                   => '09192345678',
                'address'                 => json_encode([
                    'street'   => '666 Birch Road',
                    'barangay' => 'Brgy. Matina',
                    'city'     => 'Davao City',
                    'province' => 'Davao del Sur',
                ]),
                'civil_status'            => 'single',
                'spouse_name'             => null,
                'date_of_birth'           => '1992-08-15',
                'place_of_birth'          => 'Davao City',
                'educational_attainment'  => "College (Bachelor's)",
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2023-07-15',
                'position'                => 'Finance Officer',
                'department'              => 'admin',
                'status'                  => 'active',
                'salary_rate'             => 650.00,
                'has_sss'                 => 0,
                'sss_number'              => null,
                'has_tin'                 => 0,
                'tin_number'              => null,
                'has_pagibig'             => 0,
                'pagibig_number'          => null,
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-26 02:09:57',
                'updated_at'              => '2026-02-26 02:09:57',
            ],
            [
                // The overachiever who replies to emails at 11pm
                'id'                      => 8,
                'name'                    => 'Juan Trabaho',
                'username'                => 'juan.trabaho',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'employee',
                'profile_picture'         => null,
                'remember_token'          => 'JuanTrabahoTkn',
                'first_name'              => 'Juan',
                'middle_name'             => 'Daming',
                'last_name'               => 'Trabaho',
                'email'                   => 'juan.trabaho@smartco.com',
                'phone'                   => '09171234567',
                'address'                 => json_encode([
                    'street'   => '12 Overtime St.',
                    'barangay' => 'Brgy. Cubao',
                    'city'     => 'Quezon City',
                    'province' => 'Metro Manila',
                ]),
                'civil_status'            => 'married',
                'spouse_name'             => 'Rosa Trabaho',
                'date_of_birth'           => '1995-03-14',
                'place_of_birth'          => 'Quezon City',
                'educational_attainment'  => "College (Bachelor's)",
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2021-06-01',
                'position'                => 'Senior Accountant',
                'department'              => 'admin',
                'status'                  => 'active',
                'salary_rate'             => 850.00,
                'has_sss'                 => 1,
                'sss_number'              => '34-1234567-8',
                'has_tin'                 => 1,
                'tin_number'              => '123-456-789',
                'has_pagibig'             => 1,
                'pagibig_number'          => '1234-5678-9012',
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-06 12:11:12',
                'updated_at'              => '2026-02-06 12:11:12',
            ],
            [
                // Always "on the way" but arrives 15 mins late
                'id'                      => 9,
                'name'                    => 'Maria Halos',
                'username'                => 'maria.halos',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'employee',
                'profile_picture'         => null,
                'remember_token'          => 'MariaHalosTkn1',
                'first_name'              => 'Maria',
                'middle_name'             => 'Laging',
                'last_name'               => 'Halos',
                'email'                   => 'maria.halos@smartco.com',
                'phone'                   => '09189876543',
                'address'                 => json_encode([
                    'street'   => '7 Malapit Na Ave.',
                    'barangay' => 'Brgy. Kapitolyo',
                    'city'     => 'Pasig City',
                    'province' => 'Metro Manila',
                ]),
                'civil_status'            => 'married',
                'spouse_name'             => 'Roberto Halos',
                'date_of_birth'           => '1992-07-22',
                'place_of_birth'          => 'Pasig City',
                'educational_attainment'  => "College (Bachelor's)",
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2020-01-15',
                'position'                => 'HR Officer',
                'department'              => 'admin',
                'status'                  => 'active',
                'salary_rate'             => 750.00,
                'has_sss'                 => 1,
                'sss_number'              => '34-9876543-2',
                'has_tin'                 => 1,
                'tin_number'              => '987-654-321',
                'has_pagibig'             => 1,
                'pagibig_number'          => '8765-4321-0987',
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-06 12:11:12',
                'updated_at'              => '2026-02-06 12:11:12',
            ],
            [
                // The guy who takes a 45-minute "quick break"
                'id'                      => 10,
                'name'                    => 'Carlo Pahinga',
                'username'                => 'carlo.pahinga',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'employee',
                'profile_picture'         => null,
                'remember_token'          => 'CarloPahingaTkn',
                'first_name'              => 'Carlo',
                'middle_name'             => 'Sandali',
                'last_name'               => 'Pahinga',
                'email'                   => 'carlo.pahinga@smartco.com',
                'phone'                   => '09201112222',
                'address'                 => json_encode([
                    'street'   => '3 Konting Tulog Lane',
                    'barangay' => 'Brgy. Concepcion',
                    'city'     => 'Marikina City',
                    'province' => 'Metro Manila',
                ]),
                'civil_status'            => 'married',
                'spouse_name'             => 'Ligaya Pahinga',
                'date_of_birth'           => '1998-11-05',
                'place_of_birth'          => 'Marikina City',
                'educational_attainment'  => "College (Bachelor's)",
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2022-03-10',
                'position'                => 'Bookkeeper',
                'department'              => 'admin',
                'status'                  => 'active',
                'salary_rate'             => 650.00,
                'has_sss'                 => 1,
                'sss_number'              => '34-1122334-5',
                'has_tin'                 => 1,
                'tin_number'              => '112-233-445',
                'has_pagibig'             => 1,
                'pagibig_number'          => '1122-3344-5566',
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-06 12:11:12',
                'updated_at'              => '2026-02-06 12:11:12',
            ],
        ]);
    }
}