<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Users_Seeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('users')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('users')->insert([
            [
                'id'                      => 1,
                'name'                    => 'Super Admin',
                'username'                => 'superadmin',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'superadmin',
                'profile_picture'         => null,
                'remember_token'          => 'SuperAdminToken01',
                'first_name'              => 'Super',
                'middle_name'             => null,
                'last_name'               => 'Admin',
                'email'                   => 'superadmin@example.com',
                'phone'                   => null,
                'address'                 => null,
                'civil_status'            => null,
                'spouse_name'             => null,
                'date_of_birth'           => null,
                'place_of_birth'          => null,
                'educational_attainment'  => null,
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => null,
                'position'                => null,
                'department'              => null,
                'status'                  => 'active',
                'salary_rate'             => 0,
                'has_sss'                 => 0,
                'sss_number'              => null,
                'has_tin'                 => 0,
                'tin_number'              => null,
                'has_pagibig'             => 0,
                'pagibig_number'          => null,
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-06 12:11:11',
                'updated_at'              => '2026-02-06 12:11:11',
            ],
            [
                'id'                      => 2,
                'name'                    => 'HR Manager',
                'username'                => 'hrmanager',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'hr',
                'profile_picture'         => null,
                'remember_token'          => 'PD8ffT4qLQ',
                'first_name'              => 'HR',
                'middle_name'             => null,
                'last_name'               => 'Manager',
                'email'                   => 'hr@example.com',
                'phone'                   => '09101234567',
                'address'                 => '100 Admin Street, City, Philippines',
                'civil_status'            => null,
                'spouse_name'             => null,
                'date_of_birth'           => '1985-02-10',
                'place_of_birth'          => null,
                'educational_attainment'  => null,
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2020-01-01',
                'position'                => 'HR Manager',
                'department'              => 'Human Resources',
                'status'                  => 'active',
                'salary_rate'             => 1000.00,
                'has_sss'                 => 0,
                'sss_number'              => null,
                'has_tin'                 => 0,
                'tin_number'              => null,
                'has_pagibig'             => 0,
                'pagibig_number'          => null,
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-06 12:11:11',
                'updated_at'              => '2026-02-06 12:11:11',
            ],
            [
                'id'                      => 3,
                'name'                    => 'Remittance Clerk',
                'username'                => 'remittance_clerk',
                'password'                => '$2y$12$/La9Q6JGZkIbM1G5Ah.dwOAqcGhBJbU94pUeyauuq0jgZx4Hj/tr6',
                'role'                    => 'remittance_clerk',
                'profile_picture'         => null,
                'remember_token'          => '26TRckTpBv',
                'first_name'              => 'Remittance',
                'middle_name'             => null,
                'last_name'               => 'Clerk',
                'email'                   => 'remittance@example.com',
                'phone'                   => '09111234567',
                'address'                 => '200 Clerk Street, City, Philippines',
                'civil_status'            => null,
                'spouse_name'             => null,
                'date_of_birth'           => '1993-06-15',
                'place_of_birth'          => null,
                'educational_attainment'  => null,
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2021-03-15',
                'position'                => 'Remittance Clerk',
                'department'              => 'Finance',
                'status'                  => 'active',
                'salary_rate'             => 700.00,
                'has_sss'                 => 0,
                'sss_number'              => null,
                'has_tin'                 => 0,
                'tin_number'              => null,
                'has_pagibig'             => 0,
                'pagibig_number'          => null,
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-06 12:11:11',
                'updated_at'              => '2026-02-06 12:11:11',
            ],
            [
                'id'                      => 4,
                'name'                    => 'Accountant',
                'username'                => 'accountant',
                'password'                => '$2y$12$eM2JIPsh.y4LVUlUv.xv6.VC.156R3pPLUAphTEKeFXINlqGIA5nm',
                'role'                    => 'accountant',
                'profile_picture'         => null,
                'remember_token'          => 'K0ve6RLqfM',
                'first_name'              => 'Account',
                'middle_name'             => null,
                'last_name'               => 'Ant',
                'email'                   => 'accountant@example.com',
                'phone'                   => '09121234567',
                'address'                 => '300 Accounting Street, City, Philippines',
                'civil_status'            => null,
                'spouse_name'             => null,
                'date_of_birth'           => '1990-09-20',
                'place_of_birth'          => null,
                'educational_attainment'  => null,
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2020-06-01',
                'position'                => 'Accountant',
                'department'              => 'Finance',
                'status'                  => 'active',
                'salary_rate'             => 950.00,
                'has_sss'                 => 0,
                'sss_number'              => null,
                'has_tin'                 => 0,
                'tin_number'              => null,
                'has_pagibig'             => 0,
                'pagibig_number'          => null,
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-06 12:11:12',
                'updated_at'              => '2026-02-06 12:11:12',
            ],
            [
                'id'                      => 5,
                'name'                    => 'John Doe',
                'username'                => 'johndoe',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'employee',
                'profile_picture'         => null,
                'remember_token'          => 'XxYyZzDemo1',
                'first_name'              => 'John',
                'middle_name'             => null,
                'last_name'               => 'Doe',
                'email'                   => 'employee@example.com',
                'phone'                   => '09123456789',
                'address'                 => '123 Main Street, City, Philippines',
                'civil_status'            => 'single',
                'spouse_name'             => null,
                'date_of_birth'           => '1995-05-15',
                'place_of_birth'          => null,
                'educational_attainment'  => null,
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2024-01-15',
                'position'                => 'Staff',
                'department'              => 'IT',
                'status'                  => 'active',
                'salary_rate'             => 800.00,
                'has_sss'                 => 0,
                'sss_number'              => null,
                'has_tin'                 => 0,
                'tin_number'              => null,
                'has_pagibig'             => 0,
                'pagibig_number'          => null,
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-06 12:11:12',
                'updated_at'              => '2026-02-06 12:11:12',
            ],
            [
                'id'                      => 6,
                'name'                    => 'Angela Fernandez',
                'username'                => 'angelafernandez',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'employee',
                'profile_picture'         => null,
                'remember_token'          => 'AngelaDemo123',
                'first_name'              => 'Angela',
                'middle_name'             => null,
                'last_name'               => 'Fernandez',
                'email'                   => 'angela.fernandez@example.com',
                'phone'                   => '09192345678',
                'address'                 => '666 Birch Road, Davao City',
                'civil_status'            => 'single',
                'spouse_name'             => null,
                'date_of_birth'           => '1992-08-15',
                'place_of_birth'          => null,
                'educational_attainment'  => null,
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2023-07-15',
                'position'                => 'Finance Officer',
                'department'              => 'Finance',
                'status'                  => 'active',
                'salary_rate'             => 650.00,
                'has_sss'                 => 0,
                'sss_number'              => null,
                'has_tin'                 => 0,
                'tin_number'              => null,
                'has_pagibig'             => 0,
                'pagibig_number'          => null,
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => '2026-02-26 02:09:57',
                'updated_at'              => '2026-02-26 02:09:57',
            ],

            // -------------------------------------------------------
            // WITTY EMPLOYEES — IDs 7–9
            // -------------------------------------------------------
            [
                // The overachiever who replies to emails at 11pm
                'id'                      => 7,
                'name'                    => 'Juan Trabaho',
                'username'                => 'juan.trabaho',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'employee',
                'profile_picture'         => null,
                'remember_token'          => 'JuanTrabahoTkn',
                'first_name'              => 'Juan',
                'middle_name'             => 'Daming',
                'last_name'               => 'Trabaho',
                'email'                   => 'juan.trabaho@smartco.com',
                'phone'                   => '09171234567',
                'address'                 => '12 Overtime St., Cubao, Quezon City',
                'civil_status'            => 'married',
                'spouse_name'             => 'Rosa Trabaho',
                'date_of_birth'           => '1995-03-14',
                'place_of_birth'          => 'Quezon City',
                'educational_attainment'  => "Bachelor's Degree",
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2021-06-01',
                'position'                => 'Senior Accountant',
                'department'              => 'Finance',
                'status'                  => 'active',
                'salary_rate'             => 850.00,
                'has_sss'                 => 1,
                'sss_number'              => '34-1234567-8',
                'has_tin'                 => 1,
                'tin_number'              => '123-456-789-000',
                'has_pagibig'             => 1,
                'pagibig_number'          => 'PB-1234-5678',
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => now(),
                'updated_at'              => now(),
            ],
            [
                // Always "on the way" but arrives 15 mins late
                'id'                      => 8,
                'name'                    => 'Maria Halos',
                'username'                => 'maria.halos',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'employee',
                'profile_picture'         => null,
                'remember_token'          => 'MariaHalosTkn1',
                'first_name'              => 'Maria',
                'middle_name'             => 'Laging',
                'last_name'               => 'Halos',
                'email'                   => 'maria.halos@smartco.com',
                'phone'                   => '09189876543',
                'address'                 => '7 Malapit Na Ave., Pasig City',
                'civil_status'            => 'married',
                'spouse_name'             => 'Roberto Halos',
                'date_of_birth'           => '1992-07-22',
                'place_of_birth'          => 'Pasig City',
                'educational_attainment'  => "Bachelor's Degree",
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2020-01-15',
                'position'                => 'HR Officer',
                'department'              => 'Human Resources',
                'status'                  => 'active',
                'salary_rate'             => 750.00,
                'has_sss'                 => 1,
                'sss_number'              => '34-9876543-2',
                'has_tin'                 => 1,
                'tin_number'              => '987-654-321-000',
                'has_pagibig'             => 1,
                'pagibig_number'          => 'PB-8765-4321',
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => now(),
                'updated_at'              => now(),
            ],
            [
                // The guy who takes a 45-minute "quick break"
                'id'                      => 9,
                'name'                    => 'Carlo Pahinga',
                'username'                => 'carlo.pahinga',
                'password'                => '$2y$12$YhTTF5BRZfCgAA9.G1RFyObHHru/l1suzFQ2cXZvWvYYze66mQ/hS',
                'role'                    => 'employee',
                'profile_picture'         => null,
                'remember_token'          => 'CarloPahingaTkn',
                'first_name'              => 'Carlo',
                'middle_name'             => 'Sandali',
                'last_name'               => 'Pahinga',
                'email'                   => 'carlo.pahinga@smartco.com',
                'phone'                   => '09201112222',
                'address'                 => '3 Konting Tulog Lane, Marikina City',
                'civil_status'            => 'married',
                'spouse_name'             => 'Ligaya Pahinga',
                'date_of_birth'           => '1998-11-05',
                'place_of_birth'          => 'Marikina City',
                'educational_attainment'  => "Bachelor's Degree",
                'driver_license_number'   => null,
                'driver_license_validity' => null,
                'date_of_hire'            => '2022-03-10',
                'position'                => 'Bookkeeper',
                'department'              => 'Finance',
                'status'                  => 'active',
                'salary_rate'             => 650.00,
                'has_sss'                 => 1,
                'sss_number'              => '34-1122334-5',
                'has_tin'                 => 1,
                'tin_number'              => '112-233-445-000',
                'has_pagibig'             => 1,
                'pagibig_number'          => 'PB-1122-3344',
                'signature_path'          => null,
                'attachments'             => null,
                'created_at'              => now(),
                'updated_at'              => now(),
            ],
        ]);
    }
}